# Generated by Django 2.2.6 on 2019-12-06 11:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='autos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type', models.CharField(choices=[('G', 'Good news'), ('B', 'Bad news'), ('F', 'Fake news'), ('A', 'Aliens news !?!?')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'auto',
                'verbose_name_plural': 'autos',
                'ordering': ['date_published'],
            },
        ),
    ]
