# Generated by Django 2.2.6 on 2019-12-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191115_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_published'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
